#Supabase credentials
SUPABASE_URL = "https://kxyyxdqgpilwragjraoq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4eXl4ZHFncGlsd3JhZ2pyYW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMTk3MjUsImV4cCI6MjA1NDg5NTcyNX0.WAoMfIqdOs1WMGac1Oo_NdxxN4jhmQC9Yd8B-b5Gnf8"